config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#main_page'

  resources :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :authenticate_user!

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user = current_user
		if @tweet.save
			#key = success, value = "You have created..."
			flash[:success] = "You have created a tweet"
			redirect_to new_tweet_path
		end
	end

	def index
		@tweets = Tweet.all
	end

	def tweet_params
		params.require(:tweet).permit(:content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Htwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HTwitter", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        	<%= link_to "New Tweet", new_tweet_path %>
        </li>
        <li>
        	<%= link_to "News Feed", tweets_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
        	<% if user_signed_in? %>
				<%= link_to "Log out", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Sign in", new_user_session_path, method: :get %>
			<% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
	<% flash.each do |key,value| %>
		<div class="alert alert-<%=key%>">
			<%= value %>
		</div
	<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/static_pages/main_page.html.erb
yellow robots

app/views/tweets/index.html.erb
<ul class="list-group">
	<% @tweets.each do |tweet| %>
		<li class="list-group-item">
			<%= tweet.content %>
		</li>
	<% end %>
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>